# Generated by Django 5.1.1 on 2024-11-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sizes', models.JSONField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gender', models.CharField(choices=[('men', "Men's"), ('women', "Women's")], max_length=10)),
                ('category', models.CharField(choices=[('shorts', 'Shorts'), ('shirts', 'Shirts')], max_length=10)),
                ('stock', models.PositiveIntegerField()),
            ],
        ),
    ]
