# Generated by Django 5.1 on 2024-12-13 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default='https://img.freepik.com/free-vector/coming-soon-display-background-with-focus-light_1017-33741.jpg?t=st=1734035524~exp=1734039124~hmac=adff18d75a4afbfd4b3e44cb249bfcfc467ee624b4b8b4ba928c256de9f98767&w=826', max_length=500),
        ),
    ]
